import { IsEmail, IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class CreateUserDto {
  // id is auto-increment in the DB — do not include here

  @IsString()
  @IsNotEmpty()
  name: string;

  @IsEmail()
  @IsNotEmpty()
  email: string;

  // qrCode is generated by qr-code.service.ts — include only if you want to accept a precomputed value
  @IsOptional()
  @IsString()
  qrCode?: string;
}