import { IsEmail, IsOptional, IsString, IsNotEmpty } from 'class-validator';

export class UpdateUserDto {
  @IsOptional()
  @IsString()
  @IsNotEmpty()
  name?: string;

  @IsOptional()
  @IsEmail()
  email?: string;

  // qrCode is generated by qr-code.service.ts but can be provided when updating
  @IsOptional()
  @IsString()
  qrCode?: string;
}